### ISSUE TITLE
swagger.ui chokes on received JSON

### ISSUE THREAD

**Issue by mdhooge** [Icinetic/baucis-swagger2#2]
baucis-swagger 0.2.1
swagger-ui 2.1.0

The new version of swagger-ui officially handles 2.0. But it cannot parse the description produced by baucis-swagger2. I'd like to help but I don't know where to start :-(

The problem is that `property` is `undefined` when calling `Resolver#resolveTo` in `swagger-ui.js`.
```js
Resolver.prototype.resolveTo = function (root, property, resolutionTable, location) {
  var ref = property.$ref;
```

Maybe the problem is in my Model, but swagger-ui works properly with baucis-swagger (v1).

**Comment by pjmolina** [comment]
Thanks for reporting it. Do you have a swagger.json shareable to repro it? I will investigate it.

**Comment by pjmolina** [comment]
I was able to reproduce it with this [sample](https://model-101.herokuapp.com/api/swagger.json?apikey=icinetic). It seems to be a typo on referencing a defintion by name: `"$ref": "#/definitions/Error"` however the definition is named: `ErrorModel`. 

Working on a fix.

**Comment by pjmolina** [comment]
Confirmed and fixed. All references to `"#/definitions/Error"` has been replaced for `"#/definitions/ErrorModel"` 

Fixed in **version 0.2.2**

**Comment by mdhooge** [comment]
Thanks for your quick answer… Unfortunately, this doesn't solve my problem.

You'll find 2 files over there: https://gist.github.com/mdhooge/b19f7e2a5477fe80772a

The "KO" one uses the following Schema, and cannot be parsed by swagger-ui:
```js
var ChargeAreaSchema = new Schema({
  name: {
    type: String,
    required: true
  },
  clusters: [ { type: Schema.Types.ObjectId, ref: 'ChargeCluster' } ]
});
```

For the "OK" one, I removed the clusters.

I tried to compare both (after having pretty-ied them) but there order is totally different.

HTH
Michel

**Comment by pjmolina** [comment]
Thanks for the repro data. We will investigate it. Issue reopened.

**Comment by pjmolina** [comment]
Hi @mdhooge  I think I got it. Try this sample: https://gist.githubusercontent.com/pjmolina/fe1a3335e7ca0e4ceefd/raw/340a08867445964df1e9f6336d576b0b8bd1f7d8/a.json

Validates: http://online.swagger.io/validator/debug/?url=https://gist.githubusercontent.com/pjmolina/fe1a3335e7ca0e4ceefd/raw/340a08867445964df1e9f6336d576b0b8bd1f7d8/a.json

And loads on SwaggerUI:
http://petstore.swagger.io/?url=https://gist.githubusercontent.com/pjmolina/55112ed2551af447b8d3/raw/96c050dc2d8e0f037929b036346d72f015f83f1d/swagger_array.json

Update to version 0.2.4, test is for your case and let me know if the issue is now solved.

**Comment by mdhooge** [comment]
This is much better: 4 of my 5 schemas are now visible!  :-)

I uploaded new files to Gist (https://gist.github.com/mdhooge/b19f7e2a5477fe80772a)

The problem is now with these lines (if I remove them, the whole model is visible with swagger-ui):
```js
  plugs: {
    type: [ String ],
    required: true
  },
```

BTW: I tried `http://online.swagger.io/validator/debug/?url=`, but both JSON files return an empty array.

Thanks
Michel

**Comment by pjmolina** [comment]
Nice it works for you! 
I see the poblem on plugs. The item ref is missing. I will add your case as repro unit-test and fix it.

**Comment by pjmolina** [comment]
@mdhooge it should be fixed right now on v. 0.2.5.

**Comment by mdhooge** [comment]
Yes! Everything seems OK now!

Congratulations, because my input was maybe not so helpful ;-)

**Comment by pjmolina** [comment]
Thank to you for reporting the issues. ;-)
Now the plugin support functionality that was in fact missing.
